import React, { useState, useEffect } from 'react';
import referralsApi from '../../services/referralsApi';

const ReferralDashboard = () => {
  const [referralData, setReferralData] = useState(null);
  const [referees, setReferees] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [showApplyCode, setShowApplyCode] = useState(false);
  const [applyCodeForm, setApplyCodeForm] = useState({ code: '', loading: false, error: null });
  const [copySuccess, setCopySuccess] = useState(false);

  useEffect(() => { fetchReferralData(); }, []);

  const fetchReferralData = async () => { try { setLoading(true); const [dataResponse, refereesResponse] = await Promise.all([referralsApi.getMe(), referralsApi.getMyReferees(1, 10)]); setReferralData(dataResponse.data); setReferees(refereesResponse.data.referees); setError(null); } catch (err) { setError(err.message); } finally { setLoading(false); } };

  const handleCopyLink = async () => { if (!referralData?.referral_link) return; const success = await referralsApi.copyReferralLink(referralData.referral_link); if (success) { setCopySuccess(true); setTimeout(() => setCopySuccess(false), 2000); } };
  const handleShareLink = async () => { if (!referralData?.referral_link || !referralData?.referral_code) return; await referralsApi.shareReferralLink(referralData.referral_link, referralData.referral_code); };

  const handleApplyCode = async (e) => { e.preventDefault(); setApplyCodeForm(prev => ({ ...prev, loading: true, error: null })); try { await referralsApi.applyCode(applyCodeForm.code); setShowApplyCode(false); setApplyCodeForm({ code: '', loading: false, error: null }); fetchReferralData(); } catch (err) { setApplyCodeForm(prev => ({ ...prev, loading: false, error: err.message })); } };

  if (loading) return (<div className="flex items-center justify-center min-h-64"><div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div></div>);
  if (error) return (<div className="bg-red-50 border border-red-200 rounded-lg p-4"><div className="flex items-center"><div className="text-red-500 mr-3">\u274c</div><div><h3 className="text-sm font-medium text-red-800">Erreur</h3><p className="text-sm text-red-700 mt-1">{error}</p></div></div><button onClick={fetchReferralData} className="mt-3 text-sm bg-red-100 hover:bg-red-200 text-red-800 px-3 py-1 rounded transition-colors">Reessayer</button></div>);

  const { stats, settings } = referralData || {};

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="mb-8"><h1 className="text-3xl font-bold text-white mb-2">\ud83c\udf81 Programme de Parrainage</h1><p className="text-white">Partagez Marches BTP avec vos contacts et gagnez {referralsApi.formatAmount(settings?.reward_amount || 20)} pour chaque filleul qui signe son premier contrat paye.</p></div>
      {stats && !stats.is_referred && (<div className="mb-6 bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 border border-blue-200 rounded-lg p-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-medium text-white">Vous avez ete parraine ?</h3><p className="text-sm text-white mt-1">Si quelqu'un vous a recommande Marches BTP, entrez son code pour lui faire gagner une recompense !</p></div><button onClick={() => setShowApplyCode(true)} className="bg-gradient-to-r from-orange-400 to-orange-600 hover:from-orange-300 hover:to-blue-500 transition-all duration-300 whitespace-nowrap text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors">Entrer un code</button></div></div>)}
      {showApplyCode && (<div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"><div className="bg-white rounded-lg p-6 w-full max-w-md mx-4"><h3 className="text-lg font-semibold text-gray-900 mb-4">Appliquer un code de parrainage</h3><form onSubmit={handleApplyCode}><div className="mb-4"><label className="block text-sm font-medium text-gray-700 mb-2">Code de parrainage</label><input type="text" value={applyCodeForm.code} onChange={(e) => setApplyCodeForm(prev => ({ ...prev, code: e.target.value.toUpperCase() }))} placeholder="MBTP-XXXXXX" className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 uppercase" required /></div>{applyCodeForm.error && (<div className="mb-4 text-sm text-red-600">{applyCodeForm.error}</div>)}<div className="flex space-x-3"><button type="submit" disabled={applyCodeForm.loading} className="flex-1 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-300 text-white px-4 py-2 rounded-lg font-medium transition-colors">{applyCodeForm.loading ? 'Application...' : 'Appliquer'}</button><button type="button" onClick={() => setShowApplyCode(false)} className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors">Annuler</button></div></form></div></div>)}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2">
          <div className="bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 rounded-xl shadow-sm border border-gray-200 p-6 mb-6"><h2 className="text-xl font-semibold text-white mb-4 flex items-center"><span className="mr-2">\ud83d\udd17</span>Mon lien de parrainage</h2><div className="bg-gradient-to-r from-blue-400 via-blue-500 to-blue-600 rounded-lg p-4 mb-4"><div className="flex items-center justify-between mb-3"><div><div className="text-sm font-medium text-white mb-1">Votre code :</div><div className="text-2xl font-bold text-white">{referralData?.referral_code || 'LOADING...'}</div></div><div className="text-4xl">\ud83c\udf81</div></div><div className="text-sm font-medium text-white mb-2">Votre lien :</div><div className="bg-white border rounded-lg p-3 text-sm text-gray-600 break-all">{referralData?.referral_link || 'Loading...'}</div></div><div className="flex space-x-3"><button onClick={handleCopyLink} className={`flex-1 px-4 py-2 rounded-lg font-medium transition-all ${copySuccess ? 'bg-green-100 text-green-700 border border-green-300' : 'bg-gradient-to-r from-orange-400 to-orange-600 hover:from-orange-300 hover:to-blue-500 transition-all duration-300 whitespace-nowrap text-white'}`}>{copySuccess ? '\u2705 Copie !' : '\ud83d\udccb Copier le lien'}</button><button onClick={handleShareLink} className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 bg-gradient-to-r hover:from-blue-300 hover:to-blue-500 hover:bg-gradient-to-r hover:from-blue-200 hover:to-blue-400 font-medium transition-colors">\ud83d\udce4 Partager</button></div></div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6"><div className="bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 rounded-lg shadow-sm border border-gray-200 p-4"><div className="text-2xl font-bold text-blue-600">{stats?.total_referrals || 0}</div><div className="text-sm text-white">Total filleuls</div></div><div className="bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 rounded-lg shadow-sm border border-gray-200 p-4"><div className="text-2xl font-bold text-green-600">{stats?.rewarded_referrals || 0}</div><div className="text-sm text-white">Recompenses gagnees</div></div><div className="bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 rounded-lg shadow-sm border border-gray-200 p-4"><div className="text-2xl font-bold text-purple-600">{referralsApi.formatAmount(stats?.total_rewards_earned || 0)}</div><div className="text-sm text-white">Total gagne</div></div></div>
          <div className="bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 rounded-xl shadow-sm border border-gray-200 p-6"><h2 className="text-xl font-semibold text-white mb-4 flex items-center"><span className="mr-2">\ud83d\udc65</span>Mes filleuls ({referees.length})</h2>{referees.length === 0 ? (<div className="text-center py-8 text-white"><div className="text-4xl mb-3">\ud83e\udd1d</div><p>Aucun filleul pour le moment.</p><p className="text-sm mt-1">Partagez votre lien pour commencer a gagner des recompenses !</p></div>) : (<div className="space-y-3">{referees.map((referee) => { const statusDisplay = referralsApi.getStatusDisplay(referee.status); const userIcon = referralsApi.getUserTypeIcon(referee.user.type_utilisateur); return (<div key={referee.id} className="border border-gray-200 rounded-lg p-4 hover:bg-gray-50 transition-colors"><div className="flex items-center justify-between"><div className="flex items-center"><div className="text-2xl mr-3">{userIcon}</div><div><div className="font-medium text-gray-900">{referee.user.prenom} {referee.user.nom}</div><div className="text-sm text-gray-500">Parraine le {referralsApi.formatRelativeDate(referee.referral_date)}</div></div></div><div className="text-right"><div className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${statusDisplay.bgColor} ${statusDisplay.color}`}><span className="mr-1">{statusDisplay.icon}</span>{statusDisplay.label}</div>{referee.reward && (<div className="text-sm font-medium text-green-600 mt-1">+{referralsApi.formatAmount(referee.reward.amount)}</div>)}{referee.trigger_amount && (<div className="text-xs text-gray-500 mt-1">Contrat: {referralsApi.formatAmount(referee.trigger_amount)}</div>)}</div></div></div>); })}</div>)}</div>
        </div>
        <div className="space-y-6">
          <div className="bg-gradient-to-r from-blue-500 via-blue-600 to-orange-500 rounded-xl shadow-sm border border-gray-200 p-6"><h3 className="text-lg font-semibold text-white mb-4 flex items-center"><span className="mr-2">\ud83d\udca1</span>Comment ca marche ?</h3><div className="space-y-4"><div className="flex"><div className="flex-shrink-0 w-6 h-6 bg-orange-400/20 text-orange-500 rounded-full text-sm flex items-center justify-center font-semibold mr-3 mt-0.5">1</div><div><div className="font-medium text-white text-sm">Partagez votre lien</div><div className="text-sm text-white">Envoyez votre lien de parrainage a vos contacts</div></div></div><div className="flex"><div className="flex-shrink-0 w-6 h-6 bg-orange-400/20 text-orange-500 rounded-full text-sm flex items-center justify-center font-semibold mr-3 mt-0.5">2</div><div><div className="font-medium text-white text-sm">Ils s'inscrivent</div><div className="text-sm text-white">Vos contacts s'inscrivent avec votre code</div></div></div><div className="flex"><div className="flex-shrink-0 w-6 h-6 bg-orange-400/20 text-orange-500 rounded-full text-sm flex items-center justify-center font-semibold mr-3 mt-0.5">3</div><div><div className="font-medium text-white text-sm">Premier contrat</div><div className="text-sm text-white">Ils signent et sont payes pour leur premier contrat</div></div></div><div className="flex"><div className="flex-shrink-0 w-6 h-6 bg-orange-400/20 text-orange-500 rounded-full text-sm flex items-center justify-center font-semibold mr-3 mt-0.5">4</div><div><div className="font-medium text-white text-sm">Vous gagnez !</div><div className="text-sm text-white">Recevez {referralsApi.formatAmount(settings?.reward_amount || 20)} pour chaque parrainage reussi</div></div></div></div></div>
          <div className="bg-gradient-to-r from-blue-500 via-blue-600 to-orange-500 rounded-xl shadow-sm border border-gray-200 p-6"><h3 className="text-lg font-semibold text-white mb-4 flex items-center"><span className="mr-2">\ud83d\udccb</span>Conditions</h3><ul className="space-y-2 text-sm text-gray-600"><li className="flex items-start text-white"><span className="text-orange-500 mr-2 mt-0.5">\u2713</span>Recompense de {referralsApi.formatAmount(settings?.reward_amount || 20)} par filleul</li><li className="flex items-start text-white"><span className="text-orange-500 mr-2 mt-0.5">\u2713</span>Contrat minimum de {referralsApi.formatAmount(settings?.min_contract_amount || 50)}</li><li className="flex items-start text-white"><span className="text-orange-500 mr-2 mt-0.5">\u2713</span>Maximum {settings?.max_rewards_per_referrer || 20} recompenses par parrain</li><li className="flex items-start text-white"><span className="text-orange-500 mr-2 mt-0.5">\u2713</span>Paiement immediat lors de la qualification</li></ul></div>
          <div className="bg-gradient-to-r from-blue-500 via-blue-600 to-orange-500 rounded-xl p-6 text-white"><h3 className="text-lg font-semibold mb-2">\ud83d\ude80 Besoin d'aide ?</h3><p className="text-blue-100 text-sm mb-4">Notre equipe est la pour vous accompagner dans votre strategie de parrainage.</p><button className="bg-white text-blue-600 px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-50 transition-colors">Contacter le support</button></div>
        </div>
      </div>
    </div>
  );
};

export default ReferralDashboard;
